drop table if exists Customer;
drop table if exists hibernate_sequence;
drop table if exists Operation;
drop table if exists Order;
drop table if exists Product;
drop table if exists Provider;
drop table if exists User;
create table Customer (id_customer integer not null, customer_address varchar(45), customer_email varchar(45), customer_name varchar(45), customer_phone varchar(45), Users_id_user integer, primary key (id_customer));
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Operation (id_operation integer not null, op_date date, product_quant integer, type varchar(45), Order_id_order integer, Product_id_product integer not null, Users_id_user integer, primary key (id_operation));
create table `Order` (id_order integer not null, status varchar(45), Customer_id_customer integer not null, Provider_id_provider integer not null, primary key (id_order));
create table Product (id_product integer not null, product_name varchar(45), product_type varchar(45), primary key (id_product));
create table Provider (id_provider integer not null, provider_address varchar(45), provider_email varchar(45), provider_name varchar(45), provider_phone varchar(45), primary key (id_provider));
create table User (id_user integer not null, login varchar(45), password varchar(45), role varchar(45), user_name varchar(45), primary key (id_user));
alter table Customer add constraint FK3cshgsh7d2vm9wpdmv7elpbr5 foreign key (Users_id_user) references User (id_user);
alter table Operation add constraint FK88oq5qjrhjij65hutvx156nev foreign key (Order_id_order) references `Order` (id_order);
alter table Operation add constraint FKap4icke6t65lbf1swf7u3rjs5 foreign key (Product_id_product) references Product (id_product);
alter table Operation add constraint FKt1dtalusuep6kveyy4glhxpvx foreign key (Users_id_user) references User (id_user);
alter table `Order` add constraint FK62r0twl4uf4t6cpm91uqk8ro6 foreign key (Customer_id_customer) references Customer (id_customer);
alter table `Order` add constraint FK72n8cvl3ncgbpjblfibrqa76t foreign key (Provider_id_provider) references Provider (id_provider);
